name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push Node.js image
      run: docker build -t bkshivani/node-cicd-app:latest ./apps/node-app && docker push bkshivani/node-cicd-app:latest

    - name: Build and push Python image
      run: docker build -t bkshivani/python-cicd-app:latest ./apps/python-app && docker push bkshivani/python-cicd-app:latest

    - name: Build and push Go image
      run: docker build -t bkshivani/go-cicd-app:latest ./apps/go-app && docker push bkshivani/go-cicd-app:latest
